name: FlutterAppImageCI

on: 
  push:
    paths-ignore:
    - 'README.md' 
    - 'docs/' 
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@master
        with:
          channel: beta
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      - name: Flutter setup
        run: |
          flutter config --enable-linux-desktop
      - name: Build Flutter app
        run: flutter build linux
      - name: Download appimagetool
        uses: wei/wget@v1
        with:
          args: -O appimagetool-x86_64.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
      - name: Build AppImage
        run: ./create_appimage.sh
      - uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fludm-x86_64.AppImage
          tag: ${{ github.ref }}-nightly
          body: Always up to date
          overwrite: true
